---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-manual-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-sc
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-manual-sc
  hostPath:
    path: /mnt/k8s-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-sc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-manual-sc
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-sc
  template:
    metadata:
      labels:
        app: data-exchange-sc
    spec:
      containers:
      - name: busybox-writer
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              date >> /sc/data.txt;
              sleep 5;
            done
        volumeMounts:
        - name: sc-data
          mountPath: /sc
      - name: multitool-reader
        image: wbitt/network-multitool:latest
        command: ["/bin/sh", "-c"]
        args:
          - tail -f /sc/data.txt
        volumeMounts:
        - name: sc-data
          mountPath: /sc
      volumes:
      - name: sc-data
        persistentVolumeClaim:
          claimName: pvc-local-sc
