---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-hostpath
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/k8s-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-hostpath
spec:
  volumeName: pv-local-hostpath
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-pvc
  template:
    metadata:
      labels:
        app: data-exchange-pvc
    spec:
      containers:
      - name: busybox-writer
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              date >> /pvc/data.txt;
              sleep 5;
            done
        volumeMounts:
        - name: pv-data
          mountPath: /pvc
      - name: multitool-reader
        image: wbitt/network-multitool:latest
        command: ["/bin/sh", "-c"]
        args:
          - tail -f /pvc/data.txt
        volumeMounts:
        - name: pv-data
          mountPath: /pvc
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: pvc-local-hostpath
